export interface Interests {
    InterestsEntityId: number;
    UserName: string;
    UserLocation: string;
    // Canoeing: boolean;
    // Kayaking: boolean;
    // Hiking: boolean;
    // RockClimbing: boolean;
    // Camping: boolean;
    // Fishing: boolean;
    // SightSeeing: boolean;
    // Football: boolean;
    // Basketball: boolean;
    // Soccer: boolean;
    // Baseball: boolean;
    // Hockey: boolean;
    // Tennis: boolean;
    // Golf: boolean;
    // Running: boolean;
    // WeightLifting: boolean;
    // Yoga: boolean;
    // Gymnastics: boolean;
    // Restaurants: boolean;
    // Bars: boolean;
    // Wineries: boolean;
    // Consoles: boolean;
    // BoardGames: boolean;
    // CardGames: boolean;
    // Arcades: boolean;
    // Movies: boolean;
    // Theatre: boolean;
    // Concerts: boolean;
    // Festivals: boolean;
    // Clubs: boolean;
    // Bowling: boolean;
    // Zoo: boolean;
    // Painting: boolean;
    // Knitting: boolean;
    // Pottery: boolean;
    // Museums: boolean;
    // Aquariums: boolean;
    // Galleries: boolean;
}